version: "3.8"
services:
  springboot-war-app:
    image: your-image-name
    container_name: springboot-war-app
    ports:
      - "8080:9181"
    volumes:
      - /opt/pki/Cert/keystore1.jks:/config/keystore.jks:ro
      - /var/log/app.log:/logs/app.log
    environment:
      - JAVA_OPTS=-Dserver.port=9181 \
        -Djavax.net.ssl.keyStore=/config/keystore.jks \
        -Djavax.net.ssl.keyStorePassword=changeit \
        -Dlogging.file.name=/logs/app.log
