version: "3.8"

services:
  # Your Java App
  app:
    build: .
    image: take2018/xml-signer-app:0.1
    container_name: cbe-xml-signer
    ports:
      - "8080:8080"
    environment:
      ETS_IPS_SERVER_URL: http://192.168.20.45:9001
      ETS_IPS_CERTIFICATE_DOWNLOAD_URL: http://192.168.20.45:9001/v1/cert
      ETS_IPS_TOKEN_URL: http://192.168.20.45:9001/v1/token
      ETS_EPG_ACS_CERTIFICATE_ALIAS: ets_acs
      SECURITY_PKI_KEYSTORE_FILE_LOCATION: /config/keystore.jks
      SECURITY_PKI_KEYSTORE_FILE_STORE_PASSWORD: wegagen123
      SECURITY_PKI_KEYSTORE_FILE_KEY_PASSWORD: wegagen123
      SECURITY_PKI_KEYSTORE_TYPE: JKS
      SPRING_REDIS_TIMETOLIVE: 1000
      HOME_LOG: /logs/
      POD_NAME: test_pod
      SPRING_PROFILES_ACTIVE: docker
      ETS_IPS_USERNAME: cbe
      ETS_IPS_PASSWORD: cbe1
      ETS_IPS_GRANTTYPE: password
      THREAD_COUNT: 2
    volumes:
      - C:/etswitch/national_payment_gateway/certs/keys/participants/wegagen/keystore1.jks:/config/keystore.jks:ro
      - C:/ethswitch/codes/signer/cbe_signer/xmlsigner-cbe-latest/src/main/resources/logs/:/logs
    depends_on:
      - logstash
    networks:
      - elk

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elk

  # Logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    container_name: logstash
    ports:
      - "5000:5000"  # TCP input
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    networks:
      - elk

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge
