version: "3.8"

services:
  app:
    build: .
    image: take2018/xml-signer-app:0.1
    container_name: cbe-xml-signer
    ports:
      - "8080:8080"
    volumes:
      - C:/etswitch/national_payment_gateway/certs/keys/participants/wegagen/keystore1.jks:/config/keystore.jks:ro
      - C:/ethswitch/codes/signer/cbe_signer/xmlsigner-cbe-latest/src/main/resources/logs/:/logs
