# Use Tomcat 10.1 with JDK 21 as the base image
FROM tomcat:10.1.22-jdk21

# Set environment variables
ENV JAVA_OPTS="-Dserver.port=9181 \
    -Djavax.net.ssl.keyStore=/config/keystore.jks \
    -Djavax.net.ssl.keyStorePassword=changeit \
    -Dlogging.file.name=/logs/app.log"



# Clean default webapps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy your WAR file to Tomcat webapps
COPY build/libs/ips-client-v1-0.1.war /usr/local/tomcat/webapps/xml_signer_v01.war

# Expose the application's port
EXPOSE 9181

# Start Tomcat
CMD ["catalina.sh", "run"]
